import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';

const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${interSans.variable} will-change-auto relative text-sm sm:text-base lg:text-lg televisor:text-4xl max-h-svh bg-zinc-200 text-zinc-800 font-medium antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


// Zaloguj się, aby sprawdzić plan lekcji, ogłoszenia oraz inne ważne
// informacje. Po zalogowaniu uzyskasz dostęp do aktualnych zajęć i
// funkcji aplikacji.